### ISSUE TITLE
Swagger generation should be automatically part of the build if swagger annotations are included?

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/openapi-tools#107]
**Description:**
If we have kubernetes or docker annotations in .bal files, then the k8s or dockerfile is automatically generated as part of the compilation. However, the same behaviour doesn't seem to happen with Swagger, and it is necessary to run "ballerina swagger export". It would be more consistent if the annotations caused the generation to happen

**Steps to reproduce:**
Add a swagger annotation to .bal and build.

**Affected Versions:**
All

**OS, DB, other environment details and versions:**
Any

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
The current tool supports several approaches for generating OpenAPI specifications. Providing annotation for generating swagger files will interact with several uses in the tool, which leads to making the tool depend on other Ballerina commands `ex: bal run` and it will more complex. Therefore closing this issue since we already provide options to generate spec without using the CLI command.
