### ISSUE TITLE
Incoporate OpenAPI type mapping changes

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/openapi-tools#975]
According to the constraint support, https://github.com/ballerina-platform/ballerina-standard-library/issues/2850 need to provide support for the below type validation

- [x] **Primitive type: Integer : (ballerina mapping) int**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
int32 |   | int
int64 |   | int
  | minimum | `@constraint:Int {   minValue: <value>}`
  | maximum | `@constraint:Int {   maxValue: <value>}`
  | exclusiveMinimum | `@constraint:Int {   minValueExclusive: <value>}`
  | exclusiveMaximum | `@constraint:Int {   maxValueExclusive: <value>}`
  | multipleOf | 

</div></b>

- [x] **Primitive type: float (ballerina mapping) : float**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
  | minimum | `@constraint:Float {   minValue: <value>}`
  | maximum | `@constraint:Float {   maxValue: <value>}`
  | exclusiveMinimum | `@constraint:Float {   minValueExclusive: <value>}`
  | exclusiveMaximum | `@constraint:Float {   maxValueExclusive: <value>}`
  | multipleOf | 

</div></b>

- [x] **Primitive type: Double (ballerina mapping) : decimal**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
  | minimum | `@constraint:Number {   minValue: <value>}`
  | maximum | `@constraint:Number {   maxValue: <value>}`
  | exclusiveMinimum | `@constraint:Number {   minValueExclusive: <value>}`
  | exclusiveMaximum | `@constraint:Number {   maxValueExclusive: <value>}`
  | multipleOf | 

</div></b>

- [x] **Primitive type: String (ballerina mapping) : string**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
  | minLength | `@constraint:String {   minLength: <value>}`
  | maxLength | `@constraint:Stringl {   maxLength: <value>}`
(not support from OpenAPI)  | length | `@constraint:Stringl {   length: <value>}`
  | pattern | 
</div></b>

- [x] **Array type: String (ballerina mapping) : array**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
  | minItems | `@constraint:Array {   minLength: <value>}`
  | maxItems | `@constraint:Array {   maxLength: <value>}`
  | uniqueItems | 
</div></b>

- [ ] **Object type: object schema (ballerina mapping) : record type**
<b style="font-weight:normal;" id="docs-internal-guid-6b9c5aaa-7fff-c31d-d728-867bfaa738f2"><div dir="ltr" style="margin-left:0pt;" align="left">

format | keywords | Ballerina Mapping
-- | -- | --
  | minProperties | 
  | maxProperties | 
</div></b>

- [x] Apply this for object schema to record type mapping
- [x] Apply for type definitions 
- [ ] Apply these constraints for functions parameters both remote, resource in service and client generation (ex: query parameters)
- [ ] Add the option for the client generation
- [ ] Update service resource functions
- [ ] Update client remote funtions
- [ ] Update learn page
- [ ] Update help text

**Comment by lnash94** [comment]
@shafreenAnfar, @ldclakmal Could you please verify this constraint mapping in OpenAPI to Ballerina? 🙂

**Comment by ldclakmal** [comment]
@lnash94 As explained in the comment [1] of the Constraint package proposal, during the 1st phase we support a subset of the proposed constraints.

As a summary, only following annotations will be there:

| Annotation | Compatibility type |
|---|---|
| `@constraint:Int` | `int` |
| `@constraint:float` | `float` |
| `@constraint:Number` | `int`\|`float`\|`decimal` |
| `@constraint:String` | `string` |
| `@constraint:Array` | `any[]` |

The `@constraint:Int`, `@constraint:Float` and `@constraint:Number` annotations will have the `minValue`, `maxValue`, `minValueExclusive` and `maxValueExclusive` constraints.

The `@constraint:String` and `@constraint:Array` annotation will have the `length`, `minLength` and `maxLength` constraints.

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/2850#issuecomment-1109512766

**Comment by lnash94** [comment]
Please find the below usage details of the validation attribute for `multipleOf` , `uniqueItems`

Validation Attributes | Percentage out of OpenAPI files (out of 349)
-- | --
multipleOf (Integer) | 1 -> 0.3%
uniqueItems (Arrays) | 14 -> 4.01%

Since these are not often used, we are pleased to add these attributes to OpenAPI tool once it, if are available in the constraint module? 

@ldclakmal could you please provide some input for this?

**Comment by lnash94** [comment]
The main purpose of adding the constraint validation to the OpenAPI tool is to validate the **Return/Response** and **Request** Payload in the generated ballerina resources APIs. 

- Here in the Client generation by default, we suppose not to enable constraint validation by assuming API providers have validated their APIs on their side. We will provide an option (--enable-client-validation) to enable constraint validation for the user if they are willing to validate the request and respond before sending an API call.


- But in the Service skeleton generation for **default behaviours**, we are supposed to add the `ballerina constraint` to validate the **request** and **response** payload by calling the method `validate` in the module constraint. Because adding constraint support to generate ballerina types will add value to service generation rather than the client. Then we make it a default behaviour to validate.

We would like to have an idea about the stability of adding the `ballerina constraint validation` before marking this validation as the default in-service generation side. ex: what are the limitations we will encounter using constrain validation. 

After adding constraint for the service skeleton. 
```ballerina
import ballerina/http;
import ballerina/constraint;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});
service / on ep0 {
    resource function get games(@http:Payload Team body) returns error? {
          body = check constraint:validate(body);
          // business logic
    }
}
```
@ldclakmal  @shafreenAnfar appreciate your thought for the further implementation of OpenAPI tool 🙂

**Comment by shafreenAnfar** [comment]
We had a meeting on this and finalized the way forward. @lnash94 shall we add the meeting notes here.

**Comment by lnash94** [comment]
Attendees: @hevayo , @shafreenAnfar , @ldclakmal , @keizer619 , @lnash94 
Meeting Notes: 
1. Regarding the **Request** and **Response** constraint validation:  Request and Response payload validation are handled through the http module. Then it won't be explicitly handled by code generation. 
2. Array item constrains validation with array constraint validation:  Array item validation is handled via defining another item type through the OpenAPI tool. 
Please find the attached doc for the list of issue and the meeting notes : https://docs.google.com/document/d/1RwNrZpgU9A7t9gpR_JRTzrmlNWsesC66Od2t_-hhZ3I/edit#
